version: '3.7'
services:
  mongodb:
    container_name: mongodb
    image: dicemongo
    restart: always
    env_file: env.local
    ports:
      - 27017-27109:27017-27109
    networks:
      - dice
  diceapi:
    container_name: diceapi
    image: diceapi
    restart: always
    depends_on:
      - mongodb
    env_file: env.local
    ports:
      - 8083:8083
    networks:
      - dice
networks:
  dice:
    driver: bridge